CREATE DATABASE SIRSEG_CONTENT
    DEFAULT CHARACTER SET = 'utf8mb4';

USE SIRSEG_CONTENT



CREATE TABLE HOMECONTENT 
(
    title VARCHAR(20), 
    body TEXT (5000),
    IMAGES VARCHAR(150),
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);

CREATE TABLE PROYECTCONTENT 
(
    title VARCHAR(20), 
    body TEXT (5000),
    IMAGES VARCHAR(150),
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);

CREATE TABLE TOPICCONTENT 
(
    title VARCHAR(20), 
    body TEXT (5000),
    IMAGES VARCHAR(150),
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);

CREATE TABLE  TOOLCONTENT 
(
    title VARCHAR(20), 
    body TEXT (5000),
    IMAGES VARCHAR(150),
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);


CREATE TABLE PARTNERCONTENT 
(
    title VARCHAR(20), 
    body TEXT (5000),
    IMAGES VARCHAR(150),
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);


CREATE TABLE CONTACTCONTENT 
(
    title VARCHAR(20), 
    body TEXT (5000),
    IMAGES VARCHAR(150),
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);